runtime: python39

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /about
  static_files: public/about.html
  upload: public/about.html
  secure: always

- url: /contactus
  static_files: public/contactus.html
  upload: public/contactus.html
  secure: always
  
#- url: /(.*)
#  static_files: public/\1
#  upload: public/(.*)


#runtime: python39
# api_version: 1
# threadsafe: true

#handlers:
 # - url: /
  #static_files: public/index.html
  #upload: public/index.html

#- url: /about
 # static_files: public/about.html
 # upload: public/about.html

#- url: /contactus
 # static_files: public/contactus.html
  # upload: public/contactus.html

# - url: /(.*)
 # static_files: public/\1
 # upload: public/(.*)
  # -------------
 

